export const TAG_FUNCTION_MAP = {
  F: ['CORIOLIS', 'ELECTRO MAGNETIC', 'PRESSURE DP', 'VORTEX', 'TURBINE', 'FLOW SWITCH'],
  P: ['PRESSURE REL', 'PRESSURE ABS', 'PRESSURE DP', 'PRESSURE SWITCH', 'PRESSURE GAUGE'],
  T: ['THERMOCOUPLE', 'RTD', 'TEMPERATURE SWITCH', 'THERMOMETER'],
  L: ['RADAR', 'GUIDED WAVE RADAR', 'LEVEL SWITCH', 'CAPACITIVE', 'LEVEL ULTRASON'],
  A: ['ANALYSER', 'PHMETER', 'CHROMATO', 'O2', 'H2S'],
  S: ['SPEED', 'VIBRATION', 'ACCELEROMETER'],
  V: ['CONTROL VALVE', 'ON OFF VALVE', 'SOLENOID SPRING'],
  Z: ['VALVE POSITION', 'LIMIT SWITCH'],
  H: ['HAND VALVE'],
  X: ['ALARM', 'FIRE DETECTOR', 'GAS DETECTOR HC', 'GAS DETECTOR H2S'],
};

export const FUNCTION_SIG_MAP = {
  'CORIOLIS': 'AI10', 'ELECTRO MAGNETIC': 'AI10', 'PRESSURE DP': 'AI10',
  'VORTEX': 'AI10', 'TURBINE': 'DI20', 'FLOW SWITCH': 'DI10',
  'PRESSURE REL': 'AI10', 'PRESSURE ABS': 'AI10', 'PRESSURE SWITCH': 'DI10',
  'THERMOCOUPLE': 'AI31', 'RTD': 'AI40', 'TEMPERATURE SWITCH': 'DI10',
  'RADAR': 'AI10', 'GUIDED WAVE RADAR': 'AI10', 'LEVEL SWITCH': 'DI10',
  'CAPACITIVE': 'AI10', 'LEVEL ULTRASON': 'AI10',
  'ANALYSER': 'AI12', 'PHMETER': 'AI12', 'CHROMATO': 'AI12',
  'CONTROL VALVE': 'AO10', 'ON OFF VALVE': 'DO10', 'SOLENOID SPRING': 'DO10',
  'VALVE POSITION': 'DI10', 'LIMIT SWITCH': 'DI10',
  'FIRE DETECTOR': 'DI10', 'GAS DETECTOR HC': 'AI10', 'GAS DETECTOR H2S': 'AI10',
  'SPEED': 'AI10', 'VIBRATION': 'AI10', 'ACCELEROMETER': 'AI10',
};

export const LOOP_SYSTEM_MAP = {
  'BPCS': 'DCS',
  'SIS': 'S-PLC',
  'MAINT': 'DIV',
};
